services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - instagram-network
    restart: always
    volumes:
      - ./data:/data/db

  instagram-backend:
    container_name: api
    image: pxycknomdictator/instagram-backend
    ports:
      - 9999:9999
    depends_on:
      - mongodb
    restart: always
    networks:
      - instagram-network
    env_file:
      - .env

networks:
  instagram-network:
